/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TaiKhoanRouteImport } from './routes/tai-khoan'
import { Route as TimKiemRouteImport } from './routes/tim-kiem'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as DanhSachLoaiRouteImport } from './routes/danh-sach.$loai'
import { Route as TheLoaiTenRouteImport } from './routes/the-loai.$ten'
import { Route as TruyenSlugRouteImport } from './routes/truyen.$slug'
import { Route as DocSlugSoRouteImport } from './routes/doc.$slug.$so'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiKhoanRoute = TaiKhoanRouteImport.update({
  id: '/tai-khoan',
  path: '/tai-khoan',
  getParentRoute: () => rootRouteImport,
} as any)
const TimKiemRoute = TimKiemRouteImport.update({
  id: '/tim-kiem',
  path: '/tim-kiem',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DanhSachLoaiRoute = DanhSachLoaiRouteImport.update({
  id: '/danh-sach/$loai',
  path: '/danh-sach/$loai',
  getParentRoute: () => rootRouteImport,
} as any)
const TheLoaiTenRoute = TheLoaiTenRouteImport.update({
  id: '/the-loai/$ten',
  path: '/the-loai/$ten',
  getParentRoute: () => rootRouteImport,
} as any)
const TruyenSlugRoute = TruyenSlugRouteImport.update({
  id: '/truyen/$slug',
  path: '/truyen/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocSlugSoRoute = DocSlugSoRouteImport.update({
  id: '/doc/$slug/$so',
  path: '/doc/$slug/$so',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/tim-kiem': typeof TimKiemRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/danh-sach/$loai': typeof DanhSachLoaiRoute
  '/the-loai/$ten': typeof TheLoaiTenRoute
  '/truyen/$slug': typeof TruyenSlugRoute
  '/doc/$slug/$so': typeof DocSlugSoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/tim-kiem': typeof TimKiemRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/danh-sach/$loai': typeof DanhSachLoaiRoute
  '/the-loai/$ten': typeof TheLoaiTenRoute
  '/truyen/$slug': typeof TruyenSlugRoute
  '/doc/$slug/$so': typeof DocSlugSoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/tim-kiem': typeof TimKiemRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/danh-sach/$loai': typeof DanhSachLoaiRoute
  '/the-loai/$ten': typeof TheLoaiTenRoute
  '/truyen/$slug': typeof TruyenSlugRoute
  '/doc/$slug/$so': typeof DocSlugSoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/tai-khoan'
    | '/tim-kiem'
    | '/admin'
    | '/danh-sach/$loai'
    | '/the-loai/$ten'
    | '/truyen/$slug'
    | '/doc/$slug/$so'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/tai-khoan'
    | '/tim-kiem'
    | '/admin'
    | '/danh-sach/$loai'
    | '/the-loai/$ten'
    | '/truyen/$slug'
    | '/doc/$slug/$so'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/tai-khoan'
    | '/tim-kiem'
    | '/_authenticated/admin'
    | '/danh-sach/$loai'
    | '/the-loai/$ten'
    | '/truyen/$slug'
    | '/doc/$slug/$so'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TaiKhoanRoute: typeof TaiKhoanRoute
  TimKiemRoute: typeof TimKiemRoute
  DanhSachLoaiRoute: typeof DanhSachLoaiRoute
  TheLoaiTenRoute: typeof TheLoaiTenRoute
  TruyenSlugRoute: typeof TruyenSlugRoute
  DocSlugSoRoute: typeof DocSlugSoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-khoan': {
      id: '/tai-khoan'
      path: '/tai-khoan'
      fullPath: '/tai-khoan'
      preLoaderRoute: typeof TaiKhoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim-kiem': {
      id: '/tim-kiem'
      path: '/tim-kiem'
      fullPath: '/tim-kiem'
      preLoaderRoute: typeof TimKiemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/danh-sach/$loai': {
      id: '/danh-sach/$loai'
      path: '/danh-sach/$loai'
      fullPath: '/danh-sach/$loai'
      preLoaderRoute: typeof DanhSachLoaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-loai/$ten': {
      id: '/the-loai/$ten'
      path: '/the-loai/$ten'
      fullPath: '/the-loai/$ten'
      preLoaderRoute: typeof TheLoaiTenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truyen/$slug': {
      id: '/truyen/$slug'
      path: '/truyen/$slug'
      fullPath: '/truyen/$slug'
      preLoaderRoute: typeof TruyenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$slug/$so': {
      id: '/doc/$slug/$so'
      path: '/doc/$slug/$so'
      fullPath: '/doc/$slug/$so'
      preLoaderRoute: typeof DocSlugSoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TaiKhoanRoute: TaiKhoanRoute,
  TimKiemRoute: TimKiemRoute,
  DanhSachLoaiRoute: DanhSachLoaiRoute,
  TheLoaiTenRoute: TheLoaiTenRoute,
  TruyenSlugRoute: TruyenSlugRoute,
  DocSlugSoRoute: DocSlugSoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
